export enum PartCategory {
  ENGINE = 'ENGINE',
  BRAKES = 'BRAKES',
  SUSPENSION = 'SUSPENSION',
  EXHAUST = 'EXHAUST',
  ELECTRICAL = 'ELECTRICAL',
  BODY = 'BODY',
  DRIVETRAIN = 'DRIVETRAIN',
  TYRES = 'TYRES',
  ACCESSORIES = 'ACCESSORIES',
}
